# Generated by Django 3.1 on 2020-08-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_auto_20200806_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='store_id',
            new_name='store',
        ),
    ]
